-- =========================================================
-- MITTISEVA SUPABASE DATABASE SCHEMA & RLS POLICIES
-- =========================================================
-- Run this script in the Supabase SQL Editor:
-- Dashboard -> SQL Editor -> New query -> Paste & Run
-- =========================================================

-- 1. Create PROFILES table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  phone TEXT,
  full_name TEXT,
  village TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create SOIL_TESTS table
CREATE TABLE IF NOT EXISTS public.soil_tests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farmer_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  ph NUMERIC,
  n NUMERIC,
  p NUMERIC,
  k NUMERIC,
  moisture NUMERIC,
  oc NUMERIC,
  score NUMERIC,
  test_date TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create CHAT_MESSAGES table
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farmer_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  sender TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ---------------------------------------------------------
-- Enable Row Level Security (RLS)
-- ---------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.soil_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------
-- Policies: PROFILES
-- ---------------------------------------------------------
CREATE POLICY "Users can view own profile" 
ON public.profiles FOR SELECT 
TO authenticated 
USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile" 
ON public.profiles FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile" 
ON public.profiles FOR UPDATE 
TO authenticated 
USING (auth.uid() = id);

-- ---------------------------------------------------------
-- Policies: SOIL_TESTS
-- ---------------------------------------------------------
CREATE POLICY "Users can view own soil tests" 
ON public.soil_tests FOR SELECT 
TO authenticated 
USING (auth.uid() = farmer_id);

CREATE POLICY "Users can insert own soil tests" 
ON public.soil_tests FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = farmer_id);

CREATE POLICY "Users can delete own soil tests" 
ON public.soil_tests FOR DELETE 
TO authenticated 
USING (auth.uid() = farmer_id);

-- ---------------------------------------------------------
-- Policies: CHAT_MESSAGES
-- ---------------------------------------------------------
CREATE POLICY "Users can view own chat messages" 
ON public.chat_messages FOR SELECT 
TO authenticated 
USING (auth.uid() = farmer_id);

CREATE POLICY "Users can insert own chat messages" 
ON public.chat_messages FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = farmer_id);

CREATE POLICY "Users can delete own chat messages" 
ON public.chat_messages FOR DELETE 
TO authenticated 
USING (auth.uid() = farmer_id);

-- ---------------------------------------------------------
-- Auto-create profile on Signup via Trigger
-- ---------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, phone, full_name, village)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'phone',
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'village'
  )
  ON CONFLICT (id) DO UPDATE SET
    phone = EXCLUDED.phone,
    full_name = EXCLUDED.full_name,
    village = EXCLUDED.village;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop existing trigger if present to avoid duplication
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
